[tool.poetry]
name = "vrp"
version = "0.1.0"
description = ""
authors = ["notkamonohasi <notkamonohasi@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
mypy = "^1.5.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
