name: master

on: push
jobs:
  pytest:
    name: Run tests with pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install uv
        run: pip install uv
      - name: Install dependencies for Python3
        run: uv sync
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}/src" >> $GITHUB_ENV
      - name: Test with ruff linter
        run: uv run ruff check src
      - name: Test with ruff formatter
        run: uv run ruff format --check src
      - name: Test with mypy
        run: uv run mypy src
      - name: Test with pytest
        run: uv run pytest -vv
      - name: Check swagger
        run: uv run src/openapi.py check
